# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.define "nginx-server" do |cfg|
      cfg.vm.box = "ubuntu/focal64" # 20.04 LTS
      cfg.vm.provider "virtualbox" do |vb|
        vb.name = "nginx1"
        vb.cpus = 2
        vb.memory = 2048
        #vb.customize ["modifyvm", :id, "--groups", "nginx-server"]
      end
      cfg.vm.host_name = "nginx-server"
      cfg.vm.network "private_network", ip: "192.168.1.20"
      cfg.vm.network "forwarded_port", guest: 22, host: 50010, auto_correct: true, id: "ssh"
      cfg.vm.synced_folder "../data", "/vagrant", disabled: true
      cfg.vm.provision "shell", path: "nginx_install.sh"
    end

end
