# -*- mode: ruby -*-
# vi: set ft=ruby :

N = 3

Vagrant.configure("2") do |config|
    ####################
    #    All in One    #
    ####################
    (1..N).each do |i|
      config.vm.define "openstack-0#{i}" do |cfg|
        cfg.vm.box = 'ubuntu/focal64'
        cfg.vm.provider "virtualbox" do |vb|
          vb.name = "controller-0#{i}"
          vb.cpus = 2 
          vb.memory = 4096
          vb.customize [ "modifyvm", :id, "--groups", "/openstack-allinone", "--nested-hw-virt", "on"] 
        end
     
        cfg.vm.host_name = "controller-0#{i}"
        cfg.vm.network "private_network", ip: "192.168.1.1#{i}"
        cfg.vm.network "forwarded_port", guest: 22, host: "2001#{i}", auto_correct: true, id: "ssh"
        cfg.vm.network "public_network", type: "dhcp"
        cfg.vm.synced_folder "../data", "/vagrant", disabled: true
        cfg.vm.provision "shell", path: "init.sh"
      end
    end
end



