# -*- mode: ruby -*-
# vi: set ft=ruby :

# max number of nodes
N = 3
host_names = ["controller", "compute1", "block1"]

Vagrant.configure("2") do |config|
  (1..N).each do |i|
    config.vm.define "openstack-test#{i}" do |cfg|
      # ubuntu/focal64
      # bento/ubuntu-22.04
      cfg.vm.box = "ubuntu/focal64" 
      
      cfg.vm.provider "virtualbox" do |vb|
        vb.name = "openstack-test#{i}"
        vb.cpus = 2 
        vb.memory = 2048
        vb.customize ["modifyvm", :id, "--groups", "/openstack-server"] 
      end
     
      cfg.vm.host_name = host_names[i-1]
      cfg.vm.network "private_network", ip: "192.168.1.5#{i}"
      cfg.vm.network "forwarded_port", guest: 22, host: "6005#{i}", auto_correct: true, id: "ssh"
      cfg.vm.synced_folder "../data", "/vagrant", disabled: true

      # cfg.vm.provision "shell", path: "", args: [ "", "" ]
      cfg.vm.provision "shell", path: "init.sh"
    end
  end
end



